// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutoSubmitController from "./auto_submit_controller"
application.register("auto-submit", AutoSubmitController)

import CounterController from "./counter_controller"
application.register("counter", CounterController)

import FrequencyController from "./frequency_controller"
application.register("frequency", FrequencyController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LoadingController from "./loading_controller"
application.register("loading", LoadingController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import ThemeSelectController from "./theme_select_controller"
application.register("theme-select", ThemeSelectController)

import ToastController from "./toast_controller"
application.register("toast", ToastController)
